POST http://localhost:8080/household/2/movement
Content-Type: application/json; charset=utf-8

{
  "localDate": "2022-05-10",
  "address": "경상남도 김해시 내외 중앙로 55 5층",
  "lastAddress": "Y"
}

###
PUT http://localhost:8080/household/2/movement/20220510
Content-Type: application/json; charset=utf-8

{
  "address": "경상남도 김해시 내외 중앙로 55 5층",
  "lastAddress": "Y"
}

###
DELETE http://localhost:8080/household/2/movement/20220510
